// <auto-generated />
using System;
using BKShop.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BKShop.Data.Migrations
{
    [DbContext(typeof(BKShopDbContext))]
    [Migration("20220630103755_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BKShop.Data.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SamSung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Realme"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oppo"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 6,
                            Name = "OnePlus"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vivo"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Khác"
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.Cart", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ProductID", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BKShop.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Name = "LapTop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Đồng hồ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Máy tính bảng"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sạc dự phòng"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tai nghe"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Loa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cường lực"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cáp sạc"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ốp lưng"
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "TPHCM",
                            CreatedDate = new DateTime(2022, 5, 21, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2021, 5, 21, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0123456789",
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 2,
                            Address = "TPHCM",
                            CreatedDate = new DateTime(2022, 5, 22, 13, 41, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2021, 5, 22, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0123456789",
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 3,
                            Address = "TPHCM",
                            CreatedDate = new DateTime(2022, 5, 22, 15, 23, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2021, 5, 23, 9, 34, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0123456789",
                            Status = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 4,
                            Address = "TPHCM",
                            CreatedDate = new DateTime(2022, 5, 23, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            DeliveryDate = new DateTime(2021, 5, 23, 16, 23, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0123456789",
                            Status = 4,
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 5,
                            Address = "TPHCM",
                            CreatedDate = new DateTime(2022, 5, 24, 12, 11, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0123456789",
                            Status = 2,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 6,
                            Address = "TPHCM",
                            CreatedDate = new DateTime(2022, 5, 24, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Phone = "0123456789",
                            Status = 0,
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928")
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Amount = 2,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 2,
                            Amount = 1,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 3,
                            Amount = 1,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 1,
                            Amount = 2,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 1,
                            Amount = 1,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 3,
                            Amount = 1,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 2,
                            Amount = 1,
                            Price = 10000000m
                        },
                        new
                        {
                            OrderId = 6,
                            ProductId = 3,
                            Amount = 1,
                            Price = 10000000m
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 3,
                            Capacity = "8/128",
                            CategoryId = 1,
                            Color = "Xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5458),
                            Description = "Hệ thống camera sau được trang bị tối tân, trong đó có camera chính 64 MP, camera góc siêu rộng 8 MP và camera macro 2 MP cùng camera trước 32 MP luôn sẵn sàng bắt trọn mọi cảm xúc trong khung hình, giúp người dùng thoải mái ghi lại những khoảnh khắc trong cuộc sống một cách ấn tượng nhất.",
                            Group = "reno6z",
                            Image = "oppo-reno6-z-5g-aurora.jpg",
                            Name = "Oppo Reno 6Z 5G xanh",
                            Price = 1000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5466)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Capacity = "4/64",
                            CategoryId = 1,
                            Color = "Đen",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5468),
                            Description = "Apple đã trang bị con chip mới nhất của hãng (tính đến 11/2020) cho iPhone 12 đó là A14 Bionic, được sản xuất trên tiến trình 5 nm với hiệu suất ổn định hơn so với chip A13 được trang bị trên phiên bản tiền nhiệm iPhone 11.",
                            Group = "ip12",
                            Image = "iphone-12-mini-den.jpg",
                            Name = "Iphone 12 4/64 đen",
                            Price = 1000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5469)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Capacity = "4/64",
                            CategoryId = 2,
                            Color = "Xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5470),
                            Description = "Samsung chính thức trình làng mẫu máy tính bảng có tên Galaxy Tab S7 FE, máy trang bị cấu hình mạnh mẽ, màn hình giải trí siêu lớn và điểm ấn tượng nhất là viên pin siêu khủng được tích hợp bên trong, giúp tăng hiệu suất làm việc nhưng vẫn có tính di động cực cao. Galaxy Tab S7 FE sẽ khiến bạn choáng ngợp với dụng lượng pin cực khủng 10090 mAh đảm bảo cho cường độ làm việc, giải trí liên tục trong nhiều giờ liền.",
                            Group = "ts7fe",
                            Image = "samsung-galaxy-tab-s7-fe-green.jpg",
                            Name = "Samsung Galaxy Tab S7 FE xanh",
                            Price = 10000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5471)
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Capacity = "4/64",
                            CategoryId = 1,
                            Color = "xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5472),
                            Description = "Xiaomi duy trì sự trẻ trung trong thiết kế của mình từ Redmi 9A, Redmi 9C và đến hiện tại là Redmi 9T, chiếc điện thoại mang đến tùy chọn màu nổi bật, rất phù hợp với cá tính năng động của giới trẻ.",
                            Group = "red9t",
                            Image = "xiaomi-redmi-9t-xanh.jpg",
                            Name = "Xiaomi Redmi 9T",
                            Price = 4950000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5473)
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Capacity = "8/256",
                            CategoryId = 1,
                            Color = "xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5474),
                            Description = "Xiaomi Mi 11 một siêu phẩm đến từ Xiaomi, máy cho trải nghiệm hiệu năng hàng đầu với vi xử lý Qualcomm Snapdragon 888, cùng loạt công nghệ đỉnh cao, khiến bất kỳ ai cũng sẽ choáng ngợp về smartphone này. Có thể thấy, điểm sáng trong thiết kế của Mi 11 đến từ cụm 3 camera mặt sau được đặt trong mô-đun hình vuông, được phân tầng với 2 lớp kính tạo nên sự khác biệt và nổi bật ngay từ cái nhìn đầu tiên.",
                            Group = "m11",
                            Image = "xiaomi-mi-11-xanhduong.jpg",
                            Name = "Xiaomi Mi 11 5G xanh",
                            Price = 16990000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5475)
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 5,
                            Capacity = "4/64",
                            CategoryId = 1,
                            Color = "xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5476),
                            Description = "Apple đã trang bị con chip mới nhất của hãng (tính đến 11/2020) cho iPhone 12 đó là A14 Bionic, được sản xuất trên tiến trình 5 nm với hiệu suất ổn định hơn so với chip A13 được trang bị trên phiên bản tiền nhiệm iPhone 11.",
                            Group = "ip12",
                            Image = "iphone-12-violet.jpg",
                            Name = "Iphone 12 4/64 tím",
                            Price = 20490000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5477)
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            Capacity = "4/64",
                            CategoryId = 1,
                            Color = "xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5478),
                            Description = "Apple đã trang bị con chip mới nhất của hãng (tính đến 11/2020) cho iPhone 12 đó là A14 Bionic, được sản xuất trên tiến trình 5 nm với hiệu suất ổn định hơn so với chip A13 được trang bị trên phiên bản tiền nhiệm iPhone 11.",
                            Group = "ip12",
                            Image = "iphone-12-xanh-duong.jpg",
                            Name = "Iphone 12 4/64 xanh dương",
                            Price = 20490000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5479)
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 5,
                            Capacity = "6/128",
                            CategoryId = 1,
                            Color = "xanh",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5481),
                            Description = "Năm nay, công nghệ màn hình trên 12 Pro Max cũng được đổi mới và trang bị tốt hơn cùng kích thước lên đến 6.7 inch, lớn hơn so với điện thoại iPhone 12. Với công nghệ màn hình OLED cho khả năng hiển thị hình ảnh lên đến 2778 x 1284 pixels. Bên cạnh đó, màn hình này còn cho độ sáng tối đa cao nhất lên đến 800 nits, luôn đảm bảo cho bạn một độ sáng cao và dễ nhìn nhất ngoài nắng.",
                            Group = "ip12pm",
                            Image = "iphone-12-pro-max-xanh-duong.jpg",
                            Name = "iphone 12 pro max 6/128 xanh dương",
                            Price = 30000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5481)
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 5,
                            Capacity = "6/128",
                            CategoryId = 1,
                            Color = "đen",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5483),
                            Description = "Năm nay, công nghệ màn hình trên 12 Pro Max cũng được đổi mới và trang bị tốt hơn cùng kích thước lên đến 6.7 inch, lớn hơn so với điện thoại iPhone 12. Với công nghệ màn hình OLED cho khả năng hiển thị hình ảnh lên đến 2778 x 1284 pixels. Bên cạnh đó, màn hình này còn cho độ sáng tối đa cao nhất lên đến 800 nits, luôn đảm bảo cho bạn một độ sáng cao và dễ nhìn nhất ngoài nắng.",
                            Group = "ip12pm",
                            Image = "iphone-12-pro-max-den.jpg",
                            Name = "iphone 12 pro max 6/128 đen",
                            Price = 30000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5483)
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 5,
                            Capacity = "6/128",
                            CategoryId = 1,
                            Color = "bạc",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5485),
                            Description = "Năm nay, công nghệ màn hình trên 12 Pro Max cũng được đổi mới và trang bị tốt hơn cùng kích thước lên đến 6.7 inch, lớn hơn so với điện thoại iPhone 12. Với công nghệ màn hình OLED cho khả năng hiển thị hình ảnh lên đến 2778 x 1284 pixels. Bên cạnh đó, màn hình này còn cho độ sáng tối đa cao nhất lên đến 800 nits, luôn đảm bảo cho bạn một độ sáng cao và dễ nhìn nhất ngoài nắng.",
                            Group = "ip12pm",
                            Image = "iphone-12-pro-bac.jpg",
                            Name = "iphone 12 pro max 6/128 bạc",
                            Price = 30000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5485)
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 5,
                            Capacity = "6/128",
                            CategoryId = 1,
                            Color = "vàng",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5487),
                            Description = "Năm nay, công nghệ màn hình trên 12 Pro Max cũng được đổi mới và trang bị tốt hơn cùng kích thước lên đến 6.7 inch, lớn hơn so với điện thoại iPhone 12. Với công nghệ màn hình OLED cho khả năng hiển thị hình ảnh lên đến 2778 x 1284 pixels. Bên cạnh đó, màn hình này còn cho độ sáng tối đa cao nhất lên đến 800 nits, luôn đảm bảo cho bạn một độ sáng cao và dễ nhìn nhất ngoài nắng.",
                            Group = "ip12pm",
                            Image = "iphone-12-pro-max-vang.jpg",
                            Name = "iphone 12 pro max 6/128 vàng",
                            Price = 30000000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5487)
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 5,
                            Capacity = "6/256",
                            CategoryId = 1,
                            Color = "đen",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5489),
                            Description = "Năm nay, công nghệ màn hình trên 12 Pro Max cũng được đổi mới và trang bị tốt hơn cùng kích thước lên đến 6.7 inch, lớn hơn so với điện thoại iPhone 12. Với công nghệ màn hình OLED cho khả năng hiển thị hình ảnh lên đến 2778 x 1284 pixels. Bên cạnh đó, màn hình này còn cho độ sáng tối đa cao nhất lên đến 800 nits, luôn đảm bảo cho bạn một độ sáng cao và dễ nhìn nhất ngoài nắng.",
                            Group = "ip12pm",
                            Image = "iphone-12-pro-max-den.jpg",
                            Name = "iphone 12 pro max 6/256 đen",
                            Price = 32500000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5489)
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 5,
                            Capacity = "6/256",
                            CategoryId = 1,
                            Color = "bạc",
                            CreatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5491),
                            Description = "Năm nay, công nghệ màn hình trên 12 Pro Max cũng được đổi mới và trang bị tốt hơn cùng kích thước lên đến 6.7 inch, lớn hơn so với điện thoại iPhone 12. Với công nghệ màn hình OLED cho khả năng hiển thị hình ảnh lên đến 2778 x 1284 pixels. Bên cạnh đó, màn hình này còn cho độ sáng tối đa cao nhất lên đến 800 nits, luôn đảm bảo cho bạn một độ sáng cao và dễ nhìn nhất ngoài nắng.",
                            Group = "ip12pr",
                            Image = "iphone-12-pro-bac.jpg",
                            Name = "iphone 12 pro max 6/256 bạc",
                            Price = 32500000,
                            Stock = 10,
                            UpdatedDate = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5491)
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Máy đẹp",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5539),
                            ProductId = 1,
                            Star = 5,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Tuyệt lắm",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5541),
                            ProductId = 1,
                            Star = 4,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Máy hơi yếu",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5542),
                            ProductId = 2,
                            Star = 2,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Máy còn yếu lắm",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5544),
                            ProductId = 2,
                            Star = 3,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Ngon đó",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5546),
                            ProductId = 2,
                            Star = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Good",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5547),
                            ProductId = 3,
                            Star = 5,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Yeah",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5549),
                            ProductId = 3,
                            Star = 4,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Đây là comment",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5550),
                            ProductId = 3,
                            Star = 4,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Màu sắc đẹp",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5552),
                            ProductId = 2,
                            Star = 5,
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928")
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Máy mạnh",
                            DateCreated = new DateTime(2022, 6, 30, 17, 37, 54, 760, DateTimeKind.Local).AddTicks(5554),
                            ProductId = 1,
                            Star = 5,
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de")
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "ef27abeb-e096-4cdc-a228-002f4d2890da",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d"),
                            ConcurrencyStamp = "4358d5e8-fdaa-43f7-9669-bb558a892052",
                            Description = "Customer role",
                            Name = "customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("BKShop.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            AccessFailedCount = 0,
                            Address = "AG",
                            ConcurrencyStamp = "9d51021a-94d3-4af6-8e1b-68c4397e41b7",
                            Email = "khanh@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bao Khanh",
                            NormalizedEmail = "khanh@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEK2/met+qOuHyEM8xDX2nbBXxPE836iBdZPr7eZhBRw+1uDorx6oegb9jMaK3WkADg==",
                            Phone = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("bff91064-dc92-421e-a233-d1080f630928"),
                            AccessFailedCount = 0,
                            Address = "AG",
                            ConcurrencyStamp = "4ac5eb63-5011-44b7-92a5-cb9cdc3b58ef",
                            Email = "customer1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Bao Khanh Customer",
                            NormalizedEmail = "customer1@gmail.com",
                            NormalizedUserName = "customer",
                            PasswordHash = "AQAAAAEAACcQAAAAEAcEH7zsmM71YX+b8l7NfTTDAlMIsQxIJlQyALaXSX1vnEHq/QKaXkxdhjnC25WuVw==",
                            Phone = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "customer1"
                        },
                        new
                        {
                            Id = new Guid("bff91054-dc92-421e-a233-d1080f630928"),
                            AccessFailedCount = 0,
                            Address = "AG",
                            ConcurrencyStamp = "72ce4612-1d60-44f6-8c36-0f150a35d70d",
                            Email = "customer2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "David",
                            NormalizedEmail = "customer2@gmail.com",
                            NormalizedUserName = "customer",
                            PasswordHash = "AQAAAAEAACcQAAAAEIV6b4nDUO8XuuYsFY+QOd9UACxO7DTZk6f8Nt/RbPRdFDbpeYvHUWHG1aJ4pk01jw==",
                            Phone = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "customer2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("69bd714f-9576-45ba-b5b7-f00649be00de"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        },
                        new
                        {
                            UserId = new Guid("bff91064-dc92-421e-a233-d1080f630928"),
                            RoleId = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d")
                        },
                        new
                        {
                            UserId = new Guid("bff91054-dc92-421e-a233-d1080f630928"),
                            RoleId = new Guid("54ba416f-6b89-4c53-873d-4fbd48506e6d")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("BKShop.Data.Entities.Cart", b =>
                {
                    b.HasOne("BKShop.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKShop.Data.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BKShop.Data.Entities.Order", b =>
                {
                    b.HasOne("BKShop.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BKShop.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("BKShop.Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKShop.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BKShop.Data.Entities.Product", b =>
                {
                    b.HasOne("BKShop.Data.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKShop.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BKShop.Data.Entities.Review", b =>
                {
                    b.HasOne("BKShop.Data.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BKShop.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BKShop.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BKShop.Data.Entities.Product", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BKShop.Data.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
